CREATE TABLE IF NOT EXISTS direcciones (
 id SERIAL PRIMARY KEY, usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
 direccion VARCHAR(200) NOT NULL, comuna VARCHAR(100) NOT NULL, region VARCHAR(100) NOT NULL,
 es_principal BOOLEAN NOT NULL DEFAULT FALSE, fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
