CREATE TABLE IF NOT EXISTS vendedores (
 id SERIAL PRIMARY KEY, usuario_id INTEGER NOT NULL UNIQUE REFERENCES usuarios(id) ON DELETE CASCADE,
 nombre_tienda VARCHAR(120) NOT NULL, descripcion TEXT, estado VARCHAR(30) NOT NULL DEFAULT 'activo',
 fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
