CREATE TABLE IF NOT EXISTS categorias (
 id SERIAL PRIMARY KEY, nombre VARCHAR(100) NOT NULL UNIQUE, descripcion TEXT, icono VARCHAR(80), imagen TEXT,
 fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
