CREATE TABLE IF NOT EXISTS productos (
 id SERIAL PRIMARY KEY, vendedor_id INTEGER NOT NULL REFERENCES vendedores(id) ON DELETE CASCADE,
 categoria_id INTEGER NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT, nombre VARCHAR(150) NOT NULL,
 descripcion TEXT NOT NULL, precio NUMERIC(12,2) NOT NULL CHECK(precio>0), stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0),
 estado VARCHAR(40) NOT NULL DEFAULT 'Nuevo', envio VARCHAR(120) DEFAULT 'Envío acordado con vendedor',
 activo BOOLEAN NOT NULL DEFAULT TRUE, fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
