CREATE TABLE IF NOT EXISTS producto_imagenes (
 id SERIAL PRIMARY KEY, producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
 url_imagen TEXT NOT NULL, orden INTEGER NOT NULL DEFAULT 1
);
