CREATE TABLE IF NOT EXISTS ordenes (
 id SERIAL PRIMARY KEY, comprador_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
 nombre VARCHAR(100) NOT NULL, apellido VARCHAR(100), email VARCHAR(150) NOT NULL, rut VARCHAR(20),
 direccion_envio VARCHAR(200) NOT NULL, comuna_envio VARCHAR(100), region_envio VARCHAR(100), metodo_pago VARCHAR(50) NOT NULL,
 total NUMERIC(12,2) NOT NULL CHECK(total>=0), estado VARCHAR(30) NOT NULL DEFAULT 'confirmada',
 fecha_compra TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
