CREATE TABLE IF NOT EXISTS orden_items (
 id SERIAL PRIMARY KEY, orden_id INTEGER NOT NULL REFERENCES ordenes(id) ON DELETE CASCADE,
 producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT, nombre VARCHAR(150) NOT NULL,
 precio NUMERIC(12,2) NOT NULL CHECK(precio>0), cantidad INTEGER NOT NULL CHECK(cantidad>0), subtotal NUMERIC(12,2) NOT NULL CHECK(subtotal>=0)
);
