CREATE TABLE IF NOT EXISTS pagos (
 id SERIAL PRIMARY KEY, orden_id INTEGER NOT NULL UNIQUE REFERENCES ordenes(id) ON DELETE CASCADE,
 metodo_pago VARCHAR(50) NOT NULL, monto NUMERIC(12,2) NOT NULL CHECK(monto>=0), estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
 fecha_pago TIMESTAMP, fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
