CREATE TABLE IF NOT EXISTS usuarios (
 id SERIAL PRIMARY KEY, nombre VARCHAR(100) NOT NULL, apellido VARCHAR(100) DEFAULT '',
 rut VARCHAR(20), email VARCHAR(150) NOT NULL UNIQUE, password_hash TEXT NOT NULL,
 foto TEXT, telefono VARCHAR(30), direccion VARCHAR(200), comuna VARCHAR(100), region VARCHAR(100),
 rol VARCHAR(30) NOT NULL DEFAULT 'cliente' CHECK (rol IN ('cliente','admin')),
 activo BOOLEAN NOT NULL DEFAULT TRUE, fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS direcciones (
 id SERIAL PRIMARY KEY, usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
 direccion VARCHAR(200) NOT NULL, comuna VARCHAR(100) NOT NULL, region VARCHAR(100) NOT NULL,
 es_principal BOOLEAN NOT NULL DEFAULT FALSE, fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS vendedores (
 id SERIAL PRIMARY KEY, usuario_id INTEGER NOT NULL UNIQUE REFERENCES usuarios(id) ON DELETE CASCADE,
 nombre_tienda VARCHAR(120) NOT NULL, descripcion TEXT, estado VARCHAR(30) NOT NULL DEFAULT 'activo',
 fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS categorias (
 id SERIAL PRIMARY KEY, nombre VARCHAR(100) NOT NULL UNIQUE, descripcion TEXT, icono VARCHAR(80), imagen TEXT,
 fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS productos (
 id SERIAL PRIMARY KEY, vendedor_id INTEGER NOT NULL REFERENCES vendedores(id) ON DELETE CASCADE,
 categoria_id INTEGER NOT NULL REFERENCES categorias(id) ON DELETE RESTRICT, nombre VARCHAR(150) NOT NULL,
 descripcion TEXT NOT NULL, precio NUMERIC(12,2) NOT NULL CHECK(precio>0), stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0),
 estado VARCHAR(40) NOT NULL DEFAULT 'Nuevo', envio VARCHAR(120) DEFAULT 'Envío acordado con vendedor',
 activo BOOLEAN NOT NULL DEFAULT TRUE, fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS producto_imagenes (
 id SERIAL PRIMARY KEY, producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE CASCADE,
 url_imagen TEXT NOT NULL, orden INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS carritos (
 id SERIAL PRIMARY KEY, usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
 estado VARCHAR(30) NOT NULL DEFAULT 'activo', fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_carrito_activo_usuario ON carritos(usuario_id) WHERE estado='activo';
CREATE TABLE IF NOT EXISTS carrito_items (
 id SERIAL PRIMARY KEY, carrito_id INTEGER NOT NULL REFERENCES carritos(id) ON DELETE CASCADE,
 producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE CASCADE, cantidad INTEGER NOT NULL CHECK(cantidad>0),
 precio_unitario NUMERIC(12,2) NOT NULL CHECK(precio_unitario>0), fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(carrito_id,producto_id)
);
CREATE TABLE IF NOT EXISTS ordenes (
 id SERIAL PRIMARY KEY, comprador_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
 nombre VARCHAR(100) NOT NULL, apellido VARCHAR(100), email VARCHAR(150) NOT NULL, rut VARCHAR(20),
 direccion_envio VARCHAR(200) NOT NULL, comuna_envio VARCHAR(100), region_envio VARCHAR(100), metodo_pago VARCHAR(50) NOT NULL,
 total NUMERIC(12,2) NOT NULL CHECK(total>=0), estado VARCHAR(30) NOT NULL DEFAULT 'confirmada',
 fecha_compra TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS orden_items (
 id SERIAL PRIMARY KEY, orden_id INTEGER NOT NULL REFERENCES ordenes(id) ON DELETE CASCADE,
 producto_id INTEGER NOT NULL REFERENCES productos(id) ON DELETE RESTRICT, nombre VARCHAR(150) NOT NULL,
 precio NUMERIC(12,2) NOT NULL CHECK(precio>0), cantidad INTEGER NOT NULL CHECK(cantidad>0), subtotal NUMERIC(12,2) NOT NULL CHECK(subtotal>=0)
);
CREATE TABLE IF NOT EXISTS pagos (
 id SERIAL PRIMARY KEY, orden_id INTEGER NOT NULL UNIQUE REFERENCES ordenes(id) ON DELETE CASCADE,
 metodo_pago VARCHAR(50) NOT NULL, monto NUMERIC(12,2) NOT NULL CHECK(monto>=0), estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
 fecha_pago TIMESTAMP, fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
